version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: mkdir build;sudo mkdir /build;sudo chmod +666 /build;
      - run:
          name: Get Dependencies
          command: GO111MODULE=on go get -v -d ./...
      - run:
          name: Build cmd/backsrv (amd64)
          command: cd build;GO111MODULE=on GOARCH=amd64 GOOS=linux go build -v -o backsrv ../cmd/backsrv/
      - run:
          name: Build cmd/backsrv (arm)
          command: cd build;GO111MODULE=on GOARCH=arm GOOS=linux go build -v -o backsrv_arm ../cmd/backsrv/
      - run:
          name: Build cmd/simplecli (amd64)
          command: cd build;GO111MODULE=on GOARCH=amd64 GOOS=linux go build -v -o simplecli ../cmd/simplecli
      - run:
          name: Build cmd/webviewer (amd64)
          command: cd build;GO111MODULE=on GOARCH=amd64 GOOS=linux go build -v -o webviewer ../cmd/webviewer
      - run:
          name: Build cmd/client (amd64)
          command: cd build;GO111MODULE=on GOARCH=amd64 GOOS=linux go build -v -o client ../cmd/client
      - run:
          name: Make Installation Scripts Executable
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Install Arduino Toolchain
          command: ./.circleci/install.sh
      - run:
          name: Build backend_arduino
          command: cd build;cmake ../cmd/backsrv/backend_arduino/;make -j4
      - run:
          name: Collect Binary Files
          command: cd build;cp backend_arduino.* simplecli client webviewer backsrv backsrv_arm /build;cp ../cmd/webviewer/index.html /build
      - run:
          name: Pack Up Binary Files
          command: tar -cf build.tar /build;mv build.tar /build
      - store_artifacts:
          path: /build/build.tar